---
- name: Configure MOTD Banner
  hosts: routers 
  gather_facts: false
  connection: network_cli 

  tasks:
    - name: Set MOTD banner
      cisco.ios.ios_banner:
        banner: motd
        text: "{{ motd_message }}" 
        state: present 